Global:
  debug: false
  use_gpu: true
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 50
  save_model_dir: ./PaddleOCR/output/final_hard
  save_epoch_step: 10
  eval_batch_step: [0, 7110]
  cal_metric_during_train: true
  pretrained_model: ./pretrain_models/best_accuracy_1st
  save_inference_dir: null
  use_visualdl: false
  infer_img:
  character_dict_path: ppocr/utils/dict/vi_dict_train.txt
  max_text_length: 60
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path:
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 1
  regularizer:
    name: L2
    factor: 3.0e-05
Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform: null
  Backbone:
    name: PPLCNetV3
    scale: 0.95
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 120
            depth: 2
            hidden_dims: 120
            kernel_size:
              - 1
              - 3
            use_guide: true
          Head:
            fc_decay: 1.0e-05
      - NRTRHead:
          nrtr_dim: 384
          max_text_length: 60
Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss: null
    - NRTRLoss: null
PostProcess:
  name: CTCLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: false
Train:
  dataset:
    name: MultiScaleDataSet
    ds_width: false
    data_dir: ./data_ocr
    ext_op_transform_idx: 1
    label_file_list:
      - data_ocr/1st_kalapa_ocr_train_label.txt
      - data_ocr/InkData_line_processed_label.txt
      - data_ocr/Level2_samples_label.txt
      - data_ocr/Level3_samples_label.txt
      - data_ocr/private_test_label.txt
      - data_ocr/vn_handwritten_images_label.txt
      - data_ocr/level_3/test/labels.txt
      - data_ocr/level_3/train/labels.txt
      - data_ocr/level_2/test/labels.txt
      - data_ocr/level_2/train/labels.txt
      - data_ocr/jointed_data/labels.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      # - BWTransfer: null
      # - RandomShrink: null
      # - CusAug: null
      - MultiLabelEncode:
          gtc_encode: NRTRLabelEncode
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_gtc
            - length
            - valid_ratio
  sampler:
    name: MultiScaleSampler
    scales:
      - - 720
        - 32
      - - 720
        - 48
      - - 720
        - 64
    first_bs: 32
    max_w: 1080
    fix_bs: false
    divided_factor:
      - 8
      - 16
    is_training: true
  loader:
    shuffle: true
    batch_size_per_card: 32
    drop_last: true
    num_workers: 8
    use_shared_memory: False
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./data_ocr
    label_file_list:
      - data_ocr/public_test_label.txt
      - data_ocr/level_2/valid/labels.txt
      - data_ocr/level_3/valid/labels.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      # - BWTransfer: null
      - MultiLabelEncode:
          gtc_encode: NRTRLabelEncode
      - RecResizeImg:
          image_shape:
            - 3
            - 48
            - 720
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_gtc
            - length
            - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 32
    num_workers: 8
    use_shared_memory: False
profiler_options: null
