Global:
  debug: false
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 1
  save_model_dir: ./output/final_hard
  save_epoch_step: 10
  eval_batch_step: [0, 6]
  cal_metric_during_train: true
  pretrained_model: ./pretrain_models/ocr_new_data_3epoch
  save_inference_dir: null
  use_visualdl: false
  infer_img:
  character_dict_path: ppocr/utils/dict/vi_dict_train.txt
  max_text_length: 60
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path:
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.001
  regularizer:
    name: L2
    factor: 0
Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform: null
  Backbone:
    name: PPLCNetV3
    scale: 0.95
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 120
            depth: 2
            hidden_dims: 120
            kernel_size:
              - 1
              - 3
            use_guide: true
          Head:
            fc_decay: 1.0e-05
      - NRTRHead:
          nrtr_dim: 384
          max_text_length: 60
Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss: null
    - NRTRLoss: null
PostProcess:
  name: CTCLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: false
Train:
  dataset:
    name: MultiScaleDataSet
    ds_width: false
    data_dir: /kaggle/input/d/tinphmminh/
    ext_op_transform_idx: 1
    label_file_list:
      - /kaggle/input/d/tinphmminh/handwrite-data/Handwrite_data_train_label.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      # - BWTransfer: null
      # - RandomShrink: null
      # - CusAug: null
      - MultiLabelEncode:
          gtc_encode: NRTRLabelEncode
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_gtc
            - length
            - valid_ratio
  sampler:
    name: MultiScaleSampler
    scales:
      - - 720
        - 32
      - - 720
        - 48
      - - 720
        - 64
    first_bs: 32
    max_w: 1080
    fix_bs: false
    divided_factor:
      - 8
      - 16
    is_training: true
  loader:
    shuffle: true
    batch_size_per_card: 32
    drop_last: true
    num_workers: 8
    use_shared_memory: False
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /kaggle/input/d/tinphmminh/
    label_file_list:
      - /kaggle/input/d/tinphmminh/handwrite-data/Handwrite_data_test_label.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      # - BWTransfer: null
      - MultiLabelEncode:
          gtc_encode: NRTRLabelEncode
      - RecResizeImg:
          image_shape:
            - 3
            - 48
            - 720
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_gtc
            - length
            - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 32
    num_workers: 8
    use_shared_memory: False
profiler_options: null
